
export interface Home {
  id: string;
  title: string;
  price: string;
  address: string;
  description: string;
  imageUrl: string | null; // Primary image (first from images array) - null until loaded
  images?: string[]; // All property images from Redfin API
  additionalImages?: string[]; // Legacy: additional images for mock data
  redfinUrl?: string; // Redfin detail page URL for fetching images on-demand
  listingUrl: string;
  specs: {
    beds: number;
    baths: number;
    sqft: number;
  };
  // General insights generated by AI
  insightBullets: {
    style: string;
    vibe: string;
    risk: string; // Combines flood, fire, superfund, earthquake data
    safety: string; // Crime data
    financials: string;
    schools: string;
    hospitals: string;
    transit: string;
    greenSpace: string;
  };
  // Specific matches to user's natural language prompt
  matchInsights: string[];
  analysis: {
    nature: string;
    commute: string;
    safety: string;
    schools: string;
  };
}

export interface UserPreferences {
  query: string;
  priorities: string[];
}

export enum AppState {
  LANDING = 'LANDING',
  BROWSING = 'BROWSING',
  COMPARING = 'COMPARING',
  LIKED_HOMES = 'LIKED_HOMES',
  DEEP_ANALYSIS = 'DEEP_ANALYSIS',
  SAVED_HOMES = 'SAVED_HOMES',
}

export interface User {
  googleId: string;
  email: string;
  name: string;
  picture: string;
}
