
export interface Home {
  id: string;
  title: string;
  price: string;
  address: string;
  description: string;
  imageUrl: string;
  additionalImages?: string[];
  listingUrl: string;
  specs: {
    beds: number;
    baths: number;
    sqft: number;
  };
  // General insights generated by AI
  insightBullets: {
    style: string;
    vibe: string;
    risk: string; // Combines flood, fire, superfund, earthquake data
    safety: string; // Crime data
    financials: string;
    schools: string;
    hospitals: string;
    transit: string;
    greenSpace: string;
  };
  // Specific matches to user's natural language prompt
  matchInsights: string[];
  analysis: {
    nature: string;
    commute: string;
    safety: string;
    schools: string;
  };
}

export interface UserPreferences {
  query: string;
  priorities: string[];
}

export enum AppState {
  LANDING = 'LANDING',
  BROWSING = 'BROWSING',
  COMPARING = 'COMPARING',
  LIKED_HOMES = 'LIKED_HOMES',
  DEEP_ANALYSIS = 'DEEP_ANALYSIS',
  SAVED_HOMES = 'SAVED_HOMES',
}
